In [1]:
import polars as pl
import numpy as np

In [2]:
preg = pl.read_parquet("../data/2002FemPreg.parquet")

In [3]:
preg.shape

(13593, 243)

In [4]:
preg.head()

shape: (5, 243)
┌────────┬──────────┬───────────┬───────────┬───┬──────────────┬────────┬──────┬─────────┐
│ caseid ┆ pregordr ┆ howpreg_n ┆ howpreg_p ┆ … ┆ finalwgt     ┆ secu_p ┆ sest ┆ cmintvw │
│ ---    ┆ ---      ┆ ---       ┆ ---       ┆   ┆ ---          ┆ ---    ┆ ---  ┆ ---     │
│ i64    ┆ i64      ┆ f64       ┆ f64       ┆   ┆ f64          ┆ i64    ┆ i64  ┆ i64     │
╞════════╪══════════╪═══════════╪═══════════╪═══╪══════════════╪════════╪══════╪═════════╡
│ 1      ┆ 1        ┆ null      ┆ null      ┆ … ┆ 6448.271112  ┆ 2      ┆ 9    ┆ 1231    │
│ 1      ┆ 2        ┆ null      ┆ null      ┆ … ┆ 6448.271112  ┆ 2      ┆ 9    ┆ 1231    │
│ 2      ┆ 1        ┆ null      ┆ null      ┆ … ┆ 12999.542264 ┆ 2      ┆ 12   ┆ 1231    │
│ 2      ┆ 2        ┆ null      ┆ null      ┆ … ┆ 12999.542264 ┆ 2      ┆ 12   ┆ 1231    │
│ 2      ┆ 3        ┆ null      ┆ null      ┆ … ┆ 12999.542264 ┆ 2      ┆ 12   ┆ 1231    │
└────────┴──────────┴───────────┴───────────┴───┴──────────────┴────────┴──────┴─────────┘

In [5]:
preg.columns

['caseid',
 'pregordr',
 'howpreg_n',
 'howpreg_p',
 'moscurrp',
 'nowprgdk',
 'pregend1',
 'pregend2',
 'nbrnaliv',
 'multbrth',
 'cmotpreg',
 'prgoutcome',
 'cmprgend',
 'flgdkmo1',
 'cmprgbeg',
 'ageatend',
 'hpageend',
 'gestasun_m',
 'gestasun_w',
 'wksgest',
 'mosgest',
 'dk1gest',
 'dk2gest',
 'dk3gest',
 'bpa_bdscheck1',
 'bpa_bdscheck2',
 'bpa_bdscheck3',
 'babysex',
 'birthwgt_lb',
 'birthwgt_oz',
 'lobthwgt',
 'babysex2',
 'birthwgt_lb2',
 'birthwgt_oz2',
 'lobthwgt2',
 'babysex3',
 'birthwgt_lb3',
 'birthwgt_oz3',
 'lobthwgt3',
 'cmbabdob',
 'kidage',
 'hpagelb',
 'birthplc',
 'paybirth1',
 'paybirth2',
 'paybirth3',
 'knewpreg',
 'trimestr',
 'ltrimest',
 'priorsmk',
 'postsmks',
 'npostsmk',
 'getprena',
 'bgnprena',
 'pnctrim',
 'lpnctri',
 'workpreg',
 'workborn',
 'didwork',
 'matweeks',
 'weeksdk',
 'matleave',
 'matchfound',
 'livehere',
 'alivenow',
 'cmkidied',
 'cmkidlft',
 'lastage',
 'wherenow',
 'legagree',
 'parenend',
 'anynurse',
 'fedsolid',
 'frsteatd_n',
 'frsteatd_p',
 'frsteatd',
 'quitnurs',
 'ageqtnur_n',
 'ageqtnur_p',
 'ageqtnur',
 'matchfound2',
 'livehere2',
 'alivenow2',
 'cmkidied2',
 'cmkidlft2',
 'lastage2',
 'wherenow2',
 'legagree2',
 'parenend2',
 'anynurse2',
 'fedsolid2',
 'frsteatd_n2',
 'frsteatd_p2',
 'frsteatd2',
 'quitnurs2',
 'ageqtnur_n2',
 'ageqtnur_p2',
 'ageqtnur2',
 'matchfound3',
 'livehere3',
 'alivenow3',
 'cmkidied3',
 'cmkidlft3',
 'lastage3',
 'wherenow3',
 'legagree3',
 'parenend3',
 'anynurse3',
 'fedsolid3',
 'frsteatd_n3',
 'frsteatd_p3',
 'frsteatd3',
 'quitnurs3',
 'ageqtnur_n3',
 'ageqtnur_p3',
 'ageqtnur3',
 'cmlastlb',
 'cmfstprg',
 'cmlstprg',
 'cmintstr',
 'cmintfin',
 'cmintstrop',
 'cmintfinop',
 'cmintstrcr',
 'cmintfincr',
 'evuseint',
 'stopduse',
 'whystopd',
 'whatmeth01',
 'whatmeth02',
 'whatmeth03',
 'whatmeth04',
 'resnouse',
 'wantbold',
 'probbabe',
 'cnfrmno',
 'wantbld2',
 'timingok',
 'toosoon_n',
 'toosoon_p',
 'wthpart1',
 'wthpart2',
 'feelinpg',
 'hpwnold',
 'timokhp',
 'cohpbeg',
 'cohpend',
 'tellfath',
 'whentell',
 'tryscale',
 'wantscal',
 'whyprg1',
 'whyprg2',
 'whynouse1',
 'whynouse2',
 'whynouse3',
 'anyusint',
 'prglngth',
 'outcome',
 'birthord',
 'datend',
 'agepreg',
 'datecon',
 'agecon',
 'fmarout5',
 'pmarpreg',
 'rmarout6',
 'fmarcon5',
 'learnprg',
 'pncarewk',
 'paydeliv',
 'lbw1',
 'bfeedwks',
 'maternlv',
 'oldwantr',
 'oldwantp',
 'wantresp',
 'wantpart',
 'cmbirth',
 'ager',
 'agescrn',
 'fmarital',
 'rmarital',
 'educat',
 'hieduc',
 'race',
 'hispanic',
 'hisprace',
 'rcurpreg',
 'pregnum',
 'parity',
 'insuranc',
 'pubassis',
 'poverty',
 'laborfor',
 'religion',
 'metro',
 'brnout',
 'yrstrus',
 'prglngth_i',
 'outcome_i',
 'birthord_i',
 'datend_i',
 'agepreg_i',
 'datecon_i',
 'agecon_i',
 'fmarout5_i',
 'pmarpreg_i',
 'rmarout6_i',
 'fmarcon5_i',
 'learnprg_i',
 'pncarewk_i',
 'paydeliv_i',
 'lbw1_i',
 'bfeedwks_i',
 'maternlv_i',
 'oldwantr_i',
 'oldwantp_i',
 'wantresp_i',
 'wantpart_i',
 'ager_i',
 'fmarital_i',
 'rmarital_i',
 'educat_i',
 'hieduc_i',
 'race_i',
 'hispanic_i',
 'hisprace_i',
 'rcurpreg_i',
 'pregnum_i',
 'parity_i',
 'insuranc_i',
 'pubassis_i',
 'poverty_i',
 'laborfor_i',
 'religion_i',
 'metro_i',
 'basewgt',
 'adj_mod_basewgt',
 'finalwgt',
 'secu_p',
 'sest',
 'cmintvw']

In [6]:
pregordr = preg.get_column("pregordr")
type(pregordr)

polars.series.series.Series

In [7]:
pregordr.head()

shape: (10,)
Series: 'pregordr' [i64]
[
	1
	2
	1
	2
	3
	1
	2
	3
	1
	2
]

In [8]:
def show_table(d):
    df = pl.DataFrame(d)
    df.show(None)

In [9]:
d = {
    "Value": ["1", "2", "3", "4", "5", "6", "Total"],
    "Label": [
        "LIVE BIRTH",
        "INDUCED ABORTION",
        "STILLBIRTH",
        "MISCARRIAGE",
        "ECTOPIC PREGNANCY",
        "CURRENT PREGNANCY",
        "",
    ],
    "Total": [9148, 1862, 120, 1921, 190, 352, 13593],
}

show_table(d)

Value,Label,Total
str,str,i64
"""1""","""LIVE BIRTH""",9148
"""2""","""INDUCED ABORTION""",1862
"""3""","""STILLBIRTH""",120
"""4""","""MISCARRIAGE""",1921
"""5""","""ECTOPIC PREGNANCY""",190
"""6""","""CURRENT PREGNANCY""",352
"""Total""","""""",13593

In [10]:
preg.get_column("outcome").value_counts().sort("outcome")

shape: (6, 2)
┌─────────┬───────┐
│ outcome ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 1       ┆ 9148  │
│ 2       ┆ 1862  │
│ 3       ┆ 120   │
│ 4       ┆ 1921  │
│ 5       ┆ 190   │
│ 6       ┆ 352   │
└─────────┴───────┘

In [11]:
d = {
    "Value": [".", "0-5", "6", "7", "8", "9-95", "97", "98", "99", "Total"],
    "Label": [
        "inapplicable",
        "UNDER 6 POUNDS",
        "6 POUNDS",
        "7 POUNDS",
        "8 POUNDS",
        "9 POUNDS OR MORE",
        "Not ascertained",
        "REFUSED",
        "DON'T KNOW",
        "",
    ],
    "Total": [4449, 1125, 2223, 3049, 1889, 799, 1, 1, 57, 13593],
}

show_table(d)

Value,Label,Total
str,str,i64
""".""","""inapplicable""",4449
"""0-5""","""UNDER 6 POUNDS""",1125
"""6""","""6 POUNDS""",2223
"""7""","""7 POUNDS""",3049
"""8""","""8 POUNDS""",1889
"""9-95""","""9 POUNDS OR MORE""",799
"""97""","""Not ascertained""",1
"""98""","""REFUSED""",1
"""99""","""DON'T KNOW""",57
"""Total""","""""",13593

In [12]:
counts = preg.get_column("birthwgt_lb").value_counts().sort("birthwgt_lb", nulls_last=True)
counts

shape: (21, 2)
┌─────────────┬───────┐
│ birthwgt_lb ┆ count │
│ ---         ┆ ---   │
│ f64         ┆ u32   │
╞═════════════╪═══════╡
│ 0.0         ┆ 8     │
│ 1.0         ┆ 40    │
│ 2.0         ┆ 53    │
│ 3.0         ┆ 98    │
│ 4.0         ┆ 229   │
│ …           ┆ …     │
│ 51.0        ┆ 1     │
│ 97.0        ┆ 1     │
│ 98.0        ┆ 1     │
│ 99.0        ┆ 57    │
│ null        ┆ 4449  │
└─────────────┴───────┘

In [13]:
counts[0:6]

shape: (6, 2)
┌─────────────┬───────┐
│ birthwgt_lb ┆ count │
│ ---         ┆ ---   │
│ f64         ┆ u32   │
╞═════════════╪═══════╡
│ 0.0         ┆ 8     │
│ 1.0         ┆ 40    │
│ 2.0         ┆ 53    │
│ 3.0         ┆ 98    │
│ 4.0         ┆ 229   │
│ 5.0         ┆ 697   │
└─────────────┴───────┘

In [14]:
counts.slice(0, 6).select(pl.col("count").sum().alias("total"))

shape: (1, 1)
┌───────┐
│ total │
│ ---   │
│ u32   │
╞═══════╡
│ 1125  │
└───────┘

In [15]:
preg = preg.with_columns(
    pl.when(pl.col("birthwgt_lb").is_in([51, 97, 98, 99]))
    .then(None)
    .otherwise(pl.col("birthwgt_lb"))
    .alias("birthwgt_lb")
)

In [16]:
preg.get_column("agepreg").mean()

2468.8151197039497

In [17]:
preg = preg.with_columns(pl.col("agepreg") / 100.0)
preg.get_column("agepreg").mean()

24.6881511970395

In [18]:
preg.get_column("birthwgt_oz").value_counts().sort("birthwgt_oz", nulls_last=True)

shape: (20, 2)
┌─────────────┬───────┐
│ birthwgt_oz ┆ count │
│ ---         ┆ ---   │
│ f64         ┆ u32   │
╞═════════════╪═══════╡
│ 0.0         ┆ 1037  │
│ 1.0         ┆ 408   │
│ 2.0         ┆ 603   │
│ 3.0         ┆ 533   │
│ 4.0         ┆ 525   │
│ …           ┆ …     │
│ 15.0        ┆ 378   │
│ 97.0        ┆ 1     │
│ 98.0        ┆ 1     │
│ 99.0        ┆ 46    │
│ null        ┆ 4506  │
└─────────────┴───────┘

In [19]:
preg = preg.with_columns(
    pl.when(pl.col("birthwgt_oz").is_in([97, 98, 99]))
    .then(None)
    .otherwise(pl.col("birthwgt_oz"))
    .alias("birthwgt_oz")
)

In [20]:
preg = preg.with_columns(
    totalwgt_lb=pl.col("birthwgt_lb") + pl.col("birthwgt_oz") / 16.0
)
preg.get_column("totalwgt_lb").mean()

7.265628457623368

In [21]:
weights = preg.get_column("totalwgt_lb")
n = weights.count()
n

9038

In [22]:
mean = weights.sum() / n
mean

7.265628457623368

In [23]:
weights.mean()

7.265628457623368

In [24]:
squared_deviations = (weights - mean) ** 2

In [25]:
var = squared_deviations.sum() / n
var

1.983070989750022

In [26]:
weights.var()

1.9832904288326552

In [27]:
weights.var(0)

1.9830709897500227

In [28]:
std = np.sqrt(var)
std

np.float64(1.40821553384062)

In [29]:
weights.std(0)

1.4082155338406201

In [30]:
subset = preg.filter(pl.col("caseid") == 10229)
subset.shape

(7, 244)

In [31]:
subset.get_column("outcome")

shape: (7,)
Series: 'outcome' [i64]
[
	4
	4
	4
	4
	4
	4
	1
]

## Exercises

### Exercise 1.1

Select the `birthord` column from `preg`, print the value counts, and compare to results published in the  codebook at <https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf>.

In [32]:
preg.get_column("birthord").value_counts().sort("birthord")

shape: (11, 2)
┌──────────┬───────┐
│ birthord ┆ count │
│ ---      ┆ ---   │
│ f64      ┆ u32   │
╞══════════╪═══════╡
│ null     ┆ 4445  │
│ 1.0      ┆ 4413  │
│ 2.0      ┆ 2874  │
│ 3.0      ┆ 1234  │
│ 4.0      ┆ 421   │
│ …        ┆ …     │
│ 6.0      ┆ 50    │
│ 7.0      ┆ 20    │
│ 8.0      ┆ 7     │
│ 9.0      ┆ 2     │
│ 10.0     ┆ 1     │
└──────────┴───────┘

### Exercise 1.2

Create a new column named `totalwgt_kg` that contains birth weight in kilograms (there are approximately 2.2 pounds per kilogram).
Compute the mean and standard deviation of the new column.

In [33]:
preg = preg.with_columns(totalwgt_kg=pl.col("totalwgt_lb") / 2.2)
preg.get_column("totalwgt_kg").mean(), preg.get_column("totalwgt_kg").std()

(3.3025583898288033, 0.6401333843495532)

### Exercise 1.3

What are the pregnancy lengths for the respondent with `caseid` 2298?

In [34]:
subset = preg.filter(pl.col("caseid") == 2298)
subset.get_column("prglngth")

shape: (4,)
Series: 'prglngth' [i64]
[
	40
	36
	30
	40
]

What was the birth weight of the first baby born to the respondent with `caseid` 5013?
Hint: You can use `and` to check more than one condition in a query.

In [35]:
subset = preg.filter(pl.col("caseid") == 5013)
subset.get_column("totalwgt_lb")

shape: (4,)
Series: 'totalwgt_lb' [f64]
[
	7.375
	null
	8.3125
	8.125
]

In [36]:
subset = preg.filter((pl.col("caseid") == 5013) & (pl.col("birthord") == 1))
subset.get_column("totalwgt_lb")

shape: (1,)
Series: 'totalwgt_lb' [f64]
[
	7.375
]